---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: alpine
    image: alpine:3.18
    privileged: true
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
provisioner:
  name: ansible
  inventory:
    host_vars:
      alpine:
        ansible_user: root
verifier:
  name: ansible
scenario:
  name: default